name: Fly Keep Awake
description: Keep auto-suspendable Fly.io apps awake on a schedule
author: nhedger
inputs:
  apps:
    description: A coma-separated list of names of Fly.io apps to keep awake
    required: true
  timeout:
    description: The maximum number of seconds to wait for an app to wake up
    required: false
    default: 30
  http_method:
    description: The HTTP method to use to wake up the app
    required: false
    default: GET
runs:
  using: composite
  steps:
    - name: Setup Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@1.5

    - name: Retrieve URLs of apps
      shell: bash
      id: urls
      run: |
        # Convert the comma-separated list of app names into a JSON array
        APPS=$(echo "${{ inputs.apps}}" | tr '\n' ',' | jq -R 'split(",") | map(select(length > 0))')

        # Retrieve the URLs of the apps
        URLS=$(flyctl apps list --json | jq --argjson apps "$APPS" -r '.[] | select(.Name as $name | $apps | index($name)) | .Hostname')

        # Set output variable
        echo "urls=$(echo "$URLS" | tr '\n' ' ')" >> $GITHUB_OUTPUT
      
    - name: Wake up apps
      shell: bash
      run: |
        for url in "${{ steps.urls.outputs.urls }}"; do
          echo "Waking up $url"
          curl \
            --request ${{ inputs.method }} \
            --head \
            --max-time ${{ inputs.timeout }} \
            --user-agent "Fly Keep Awake / https://github.com/nhedger/fly-keep-awake" \
            --verbose \
            "https://$url"
        done
